# Generated by Django 2.1.5 on 2019-02-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分区名')),
                ('set_count', models.IntegerField(default=10, verbose_name='座位数')),
            ],
            options={
                'verbose_name': '座位分区',
                'verbose_name_plural': '座位分区',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_no', models.CharField(max_length=20, verbose_name='座位号')),
                ('status', models.BooleanField(verbose_name='预定状态')),
                ('user', models.CharField(blank=True, max_length=50, verbose_name='预定人')),
                ('price', models.IntegerField(default=100, verbose_name='价格')),
                ('end_day', models.DateField(auto_now=True, verbose_name='结束时间')),
                ('counts', models.IntegerField(default=0, verbose_name='预订次数')),
                ('order', models.IntegerField(default=0, verbose_name='优先级')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Area', verbose_name='所在区')),
            ],
            options={
                'verbose_name': '座位管理',
                'verbose_name_plural': '座位管理',
            },
        ),
    ]
